version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:9.3.0
    steps:
      - checkout
      - run:
          name: Install Deps
          command: yarn install
      - run:
          name: Build Assets
          command: yarn build
